FROM docker.io/blackdex/rust-musl:arm-musleabihf

WORKDIR /usr/src/homebot
COPY . .

RUN cargo install --path .

FROM docker.io/arm32v5/debian:stable-slim

ENV RUST_LOG=info

RUN apt-get update \
    && apt-get install -y ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /cargo/bin/home /usr/local/bin/home

ENTRYPOINT ["home"]
