FROM docker.io/rust:1.66.0 AS builder

ENV CARGO_NET_GIT_FETCH_WITH_CLI=true

WORKDIR /usr/src/homebot
COPY . .

RUN apt-get update \
    && apt-get install -y pkg-config libssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install --path .

FROM debian:buster-slim

ENV RUST_LOG=info

RUN apt-get update \
    && apt-get install -y ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/cargo/bin/home /usr/local/bin/home

ENTRYPOINT ["home"]
