FROM ghcr.io/tunix/rust-arm32v6 AS builder

COPY container/arm/cargo.config /cargo/.config

WORKDIR /usr/src/homebot
COPY . .

RUN apt-get update \
    && apt-get install -y pkg-config libssl-dev musl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN rustup target add arm-unknown-linux-musleabihf \
    && cargo install --target=arm-unknown-linux-musleabihf --path .

FROM docker.io/arm32v5/debian:stable-slim

ENV RUST_LOG=info

RUN apt-get update \
    && apt-get install -y ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /cargo/bin/home /usr/local/bin/home

ENTRYPOINT ["home"]
