name: build-armv6

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build_armv6.yaml'
      - 'config/**'
      - 'src/**'
      - 'Cargo.*'
      - '**/Containerfile.armv6'

jobs:
  build-armv6:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./container/Containerfile.armv6
          push: true
          tags: ghcr.io/tunix/homebot:armv6
