name: build

on:
  push:
    branches:
      - main
    paths:
      - 'config/**'
      - 'src/**'
      - 'Cargo.*'
      - '**/Containerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # https://yaleman.org/post/2022/2022-10-23-docker-rust-cargo-and-137-errors/
      CARGO_NET_GIT_FETCH_WITH_CLI: true

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./container/Containerfile
          push: true
          tags: ghcr.io/tunix/homebot
          platforms: linux/amd64, linux/arm64
